### ISSUE TITLE
Ender Pearl (reusable) thrown into the void is deleted and doesn't go back into inventory

### ISSUE THREAD

**Issue by Pugsworth** [maruohon/enderutilities#10]
If you were to throw an Ender Pearl (reusable) into the void, it just drifts down until is deleted by the game. However, it doesn't go back to your inventory like expected.

Is this as intended?

**Comment by maruohon** [comment]
Oh, hmm.That is actually a good question (whether it's intended or not).

I guess I'll see if I can fix it easily. Well I guess one way is to check if the pearl entity is the non-elite one and if its y-coordinate is < 0, then return it, since it can't hit anything anymore. Well actually, I also need to check that the motionY is negative too so that it is going down within the void, that way you could still throw them upwards if you fall into the void... Unless I can easily detect when the entity dies, not sure if setDead() is called when the entity is killed in the void, I'll have to test it.
