### ISSUE TITLE
handy bag crash client

### ISSUE THREAD

**Issue by Drakemilember** [maruohon/enderutilities#107]
when i have a buff or debuff and i try to open my inventory with a handy bag be it large or the normal my clien crash and when i press shift+e to open inventory without the handy bag i don crash need help last 1.12.2 version of the mod

**Comment by maruohon** [comment]
Please post the crash log on pastebin. Without it I have no idea why it happens, as I'm pretty sure I've tested this before without issues in my dev environment.

**Comment by Drakemilember** [comment]
here the crash report [https://pastebin.com/8xwRFvBD](url)

**Comment by maruohon** [comment]
Looks like you need a newer Forge version. You need at least Forge build 2783.

This change was made already on 2019-04-19 in EnU version 0.7.13, so that Forge version you are using is very old. Unfortunately I didn't notice to update the required Forge version at that point in the mod dependencies.

**Comment by Drakemilember** [comment]
ok il try updating it and see if they work now

**Comment by Drakemilember** [comment]
its working now thanks for the help
