### ISSUE TITLE
Ender bow requires a vanilla arrow in the inventory or it wont fire

### ISSUE THREAD

**Issue by plazia** [maruohon/enderutilities#11]
Ender bow requires a vanilla arrow in the inventory or it wont fire. It wont consume the vanilla arrow. Instead it will correctly consume its Ender Arrow. But it simply refuses to fire unless I have a vanilla arrow in my inventory.

enderutilities-1.7.10-0.5.0

**Comment by maruohon** [comment]
Huh, well I have no idea how you managed that... :D
I just tested it to make sure, and it works just as it is supposed to for me.
A vanilla arrow in the inventory makes no difference, it is not checked for anywhere. At least not in my mod...

Just to make sure you understand the Ender Bow:
- if the bow is in "TP Self" mode (purple texture, toggle the mode with F by default), then it doesn't need any modules installed, just some Ender Arrows in the inventory
- if the bow is in "TP Target" mode (green texture), then it needs an Ender Capacitor and at least one location type Link Crystal installed (use the Tool Workstation to install modules), and the Link Crystal needs to have a target position set (sneak + right click with the bow after the Link Crystal(s) are installed), plus it needs the Ender Arrows in the inventory.

So I have no idea how you managed to get it to fire by having vanilla arrows in the inventory... Is it maybe some other mod affecting it? Did you download the mod from my official CurseForge project page, so that the mod itself isn't altered by some third party site?

**Comment by plazia** [comment]
Yeah I've used the tool workstation and have a capacitor and a couple of location crystals in it and I've successfully teleported mobs back to my base so I'm familiar with it's operation.  It's just it's refusing to fire unless I have a vanilla arrow in my inventory.

I suspect as you say then - it could be another mod modifying the behaviour of bows. I do run many many other mods. It's strange though because hold right click does absolutely nothing with the ender bow. Yet as soon as I add a vanilla arrow to my inventory it fires. Weird. 

Sorry to have troubled you. I suspect it's nothing wrong with your (wonderful btw) mod. I'll try and test this later in a vanilla 1.7.10 instance and thereby eliminate the possibility that it's in fact Ender Utilities. I'll report back if/when able.

**Comment by maruohon** [comment]
Alright. I'm actually interested to hear if you manage to track down which mod is causing the behaviour. From the top of my head I don't even know how they would possibly affect it this way. At least the pulling the bow part should happen regardless, I don't know how another mod would be able to prevent that based on if there are vanilla arrows in the inventory, or more precisely how they would know that the item being used (the Ender Bow) is actually any kind of bow at all, since I'm not basing that on the vanilla Bow item class. Do the Ender Porters work correctly? Because they have a similar "hold and then release" functionality (similar in code at least), and if another mod is somehow preventing items from doing that without vanilla arrows, then it might affect those too... And the Wand of the Lazy Builder's walls and cube modes.

Are you playing a custom pack or some ready made pack? Just wondering about tracking down the mod that might be causing this...

**Comment by maruohon** [comment]
Oh wait actually... I do know how they would prevent this, I just don't know why they would do it based on having vanilla arrows in the inventory. I'm using the ArrowNockEvent in my bow, if some mod cancels that event then bow doesn't start to "get used". Since my bow isn't a weapon, I think I will remove that event, since it doesn't exactly make sense for my bow. That should fix this issue.

**Comment by maruohon** [comment]
I uploaded version 0.5.1 for MC 1.7.10 to CurseForge, which should fix this issue.
For MC 1.8.9, I'll release this fix some time later, since there are also some other things that need to be done/fixed...
