### ISSUE TITLE
Feature Request: Seperate Bag/Vanilla inventory keys

### ISSUE THREAD

**Issue by Thiana** [maruohon/enderutilities#13]
Could you please have an option to not have the vanilla inventory key default to the equipped bag inventory? Some mods don't play well with expanded inventories so a separate open bag inventory key would be better.

Thanks.

**Comment by maruohon** [comment]
Sure I can add an option to disable it. However, I would rather not add another key bind, since I have gotten this far by using just the one key bind with dozens of different modifier combinations, lol :D
(Basically mods already have so many key binds that it is really difficult to assign them all without conflicts, so I'd like to only have one in my mod.)

So my question to you would be, which option would you prefer:
1) Just a straight option to disable the vanilla inventory opening the bag's inventory (you can still open the bag by right clicking with it)
2) Make the option able to swap the bag opening to happen while sneaking and normal inventory opens while not sneaking, whereas now it is the other way around.
3) Make the one key bind I have open the bag instead. The problem with this is the Inventory Swapper - since it also works while not selected. Should I then trigger the action on the item that is found first in the inventory? Another problem is that if you have any other item of mine in your hand (that uses key binds...), then that one will eat the key bind action instead and you would have to first select an item that isn't from my mod...
4) Break my stance on the only-one-keybind and add another one dedicated to the Handy Bag
5) Something else you can think of that would be easier to use?

**Comment by Thiana** [comment]
I completely missed the shift open ability :/ Though I do think an option to reverse the behavior would be nice.

**Comment by maruohon** [comment]
Ok so I'll add the option to reverse that behaviour :)
