### ISSUE TITLE
Item dupes with Ender bags

### ISSUE THREAD

**Issue by MrTubzy456** [maruohon/enderutilities#18]
Ok, there's two mods at work here but I don't know which is causing this issue so you both get a post. When using the ender bag, from Ender Utilities, and you middle click to sort your inventory from cpw's inventory sorting mod, everything dupes. Everything in the bag and your inventory. It'll fill your inventory and all of the excess won't be duped.

Here's the link to the post I made on the other mods git:https://github.com/cpw/inventorysorter/issues/18

**Comment by maruohon** [comment]
This is a known issue, and has been fixed in my dev version by basically preventing Inventory Sorter from working in any of my inventories. (It does not only dupe items, but can also destroy items, depending on how the sorting order goes...) I currently have my own sort buttons for all of my "Large Stacks" inventories, so hopefully disabling Inventory Sorter in my inventories won't be a huge issue for anyone.

Which MC version are you on? This dev version is for 1.9+ only, but I might backport this fix for the 1.8.9 branch too since this bug is pretty fatal.

**Comment by MrTubzy456** [comment]
I'm on version 1.9. If the dev version is available through curse I'll add that update to my pack on next update release.

**Comment by maruohon** [comment]
It's not available yet. (Too many changes and incomplete code to give it to anyone officially yet.) I'll try to finish some changes/improvements to the Wand of the Lazy Builder as soon as possible, and after that I just need to make sure I didn't break anything major (ie. do a round of testing on my test server) and then I'll do a new release. So hopefully within a couple of days...

**Comment by MrTubzy456** [comment]
No problem. I think I'm the only one on my server that knows about it. I haven't had anyone post any issues on my git about it either. So for the most part it's not known. Thanks for responding so quickly. Take your time on the update. I can wait until you get that all cleared up and if anyone comes to me with the issue I can say it's being taken care of.

**Comment by maruohon** [comment]
Closing this since it was fixed/worked around in 0.6.0.
