### ISSUE TITLE
crash upon startup with latest forge 1.9.4 build 1980

### ISSUE THREAD

**Issue by SDUBZ** [maruohon/enderutilities#19]
crash report:
[crash-2016-06-23_15.36.06-client.txt](https://github.com/maruohon/enderutilities/files/329259/crash-2016-06-23_15.36.06-client.txt)

client latest:
[fml-client-latest.txt](https://github.com/maruohon/enderutilities/files/329260/fml-client-latest.txt)

dont know why its crashing hope you can fix this issue so it doesnt happen in future releases

i will test with older releases to see if it loads but i thought id let you know just incase

**Comment by SDUBZ** [comment]
does work with build 1.9.4-1976

**Comment by maruohon** [comment]
Ah, this is because of the re-licensing of Forge to LGPL v2.1 in the most recent versions. They were unable to get in touch with three of the authors I believe, and thus they ended up reverting the contributions those authors had made to Forge. One of those happened to be the addition of the PlayerOpenContainerEvent, ie. it is now gone (hopefully temporarily...). To fix this crash I'll have to remove that event, which will break the Ender Bag's ability to open the GUIs unless you are standing right next to the target block (I think the Ender Chest mode in it will still work).

**Comment by BrisingrAerowing** [comment]
As my relatives say, Carp!

**Comment by johnneijzen** [comment]
Sadly the one who add that commit for PlayerOpenContainerEvent 
https://github.com/MinecraftForge/MinecraftForge/commit/8d0b58ee6fe1dca88f5874a9dd08368b0f5859e6
did not use his account for years of looks. It was added in Oct 5, 2013 that is 3 year ago i hope that he will show up or something is gonna replace that.

**Comment by maruohon** [comment]
There is a new PR open for a new event already, but from the looks of it, that one will not allow me to force the container to stay open. So I might go ahead and finally take a look at changing the bag to simply offer the slots from the inventory instead of trying to open it using the original GUI (what I've been talking about in places for ages already... >_>). That one might have its own issues with derpy client-side behaviour with "non-regular" inventories though...

**Comment by maruohon** [comment]
I'm closing this, as the crash was due to bugged Forge builds that included the 1.10 changes. Using build 1976 (or perhaps 1987?) things should be fine.
