### ISSUE TITLE
Ender Bag Crash

### ISSUE THREAD

**Issue by LiamHammett** [maruohon/enderutilities#2]
Binding the ender bag to any inventory works for opening the GUI, I've tried this with a variety of different inventories such as the ME Chest, Draconic Chest (from Draconic Evolution), Binnie's Containers, BiblioCraft blocks, Refined Relocation sorting chests, etc. and they all work fine when you're relatively close to them.

However upon leaving the area so the blocks are out of render distance, trying to right-click with the bag causes the client to crash with the following error. http://paste.ee/p/8YwOy (there's a lot of mods in this instance but I tested in an instance with just a couple of mods and the same error occurs).

I've tried both unloading and chunkloading the area the bound inventory is in, but neither seems to make a difference.

**Comment by maruohon** [comment]
This is due to the way that Minecraft works internally. This is why only vanilla blocks are whitelisted by default, because they are just about the only things that work to some extent. The issue has been discussed in more detail on the Ender Utilities MCF thread (page 2 I believe). Basically, everything breaks if the target blocks and its Tile Entity are not loaded on the client. Chunk loading only affects things on the server side, so it doesn't matter.

It _might_ be possible to allow access to simple inventories by exposing their slots, and not use the original GUI. I haven't had time to try it out yet though.

I'll close this issue, since in the current way of doing things there is nothing I can do to fix this, and the whitelist is there to prevent crashes on the default setup.
