### ISSUE TITLE
[1.10.2] Advanced Ender Porter makes player invisible/breaks beds

### ISSUE THREAD

**Issue by C0rn3j** [maruohon/enderutilities#22]
This is inconsistent, but seems like a few ports are enough to make the player completely invisible to others. 
When a player is in this state they cannot even push other players around by walking into them, and if a player enters bed they can't leave (clicking the leave button does nothing) and the view is a bit glitchy.
This seems to be fixed when porting again a few times?

forge-1.10.2-12.18.0.2010-installer.jar
enderutilities-1.10.2-0.6.5-beta.1.jar

Rest of the mods: 
http://pastebin.com/pS3DyxP8

**Comment by maruohon** [comment]
Is this while teleporting inside the same dimension, or between different dimensions, or both?
Would the bed be the best way to test this out in single player, or does this even happen in single player? Sounds like something that will be a pain to try to debug... ;_;

**Comment by c0rn3j** [comment]
Sadly I have no idea when it happens, we only used cross dimension teleporters. 
TPing inside of the same dimension doesn't seem to fix the player state. Dying does.
Seems to happen even with only 2 dimension crystals in too, so no 3+ dimensions shenanigans. 
We'll debug it a bit more.

**Comment by maruohon** [comment]
That might help yeah... do you use IRC or Discord? Or I guess the Curse client would also work, so that we don't have to discuss things in this issue thread in instant messaging manner.

I'm going to eat now, but I could try to join your server in about an hour or so, if someone is going to be online then? I'm on IRC on esper.net with the nick masa, or in Discord I think you should be able to add my with the name/tag masa#5718

**Comment by c0rn3j** [comment]
I seem to be too dumb to connect to esper with the default gnome IRC client. 
I'm either on Freenode in room #C0rn3j, Telegram as @c0rn3j, Mumble @ c0rn3j.com or Steam as C0rn3j.

**Comment by c0rn3j** [comment]
Further testing:
Apparently I can now reproduce this 100% of the time. I just need to teleport between 2 areas that are not loaded very quickly.

**Comment by maruohon** [comment]
Does the player remain in this bugged state indefinitely unless they teleport again? Or if two testing players remain in the same area for some time, does the one who is invisible eventually become visible? What happens if the bugged players tries to place or break blocks, both insta-breakable like slime blocks and regular ones like cobblestone? What happens if the player tries to mount an entity, for example ride a horse or a pig or a minecart or a boat? Does moving about (but staying close to the other player) fix it? Specifically moving/walking to different chunks, but staying close to the observing player. What about moving/walking out of range of the other player and then back (without teleporting)? (Although if the player state is bugged so that beds etc are broken, this probably wouldn't fix it, but would be useful to know anyway...) Can the bugged player load chunks when they walk along the terrain? Can hostile mobs target them? Can they attack mobs?

**Comment by c0rn3j** [comment]
>Does the player remain in this bugged state indefinitely unless they teleport again? 

Seems like they need to TP cross dimension or die to fix it.

> does the one who is invisible eventually become visible?

Not unless they TP/die/relog it seems.

> What happens if the bugged players tries to place or break blocks
Normal behavior.

>What happens if the player tries to mount an entity, for example ride a horse or a pig or a minecart or a boat?

Not tested and I'm busy atm to test it.

>Does moving about (but staying close to the other player) fix it? 

Doesn't seem like it, additionally bugged player cannot bump into other player to move them around.

> What about moving/walking out of range of the other player and then back (without teleporting)? 

No idea.

> Can the bugged player load chunks when they walk along the terrain?  

The problem wasn't first noticed until people tried to use beds in that state, so I'm assuming it's fine. (especially since there are fast jetpacks in the server)

>Can they attack mobs?

Pretty sure they can. Bugged player can attack other players for sure, and normal players can't attack bugged players since they can't see them(Even aiming at the spot where player is supposed to be doesn't help)

>Can hostile mobs target them? 

No idea, sorry. Probably yes.

**Comment by maruohon** [comment]
I'm closing this, because this is a vanilla bug and has happened to me several times on my vanilla 1.10.2 server.
