### ISSUE TITLE
[1.10.2] Portal Scaler server crash

### ISSUE THREAD

**Issue by c0rn3j** [maruohon/enderutilities#23]
Server forge: 2010; Client forge: 2014;

Modlist: http://pastebin.com/cY5NiPqn

Settings were X64, Y2, Z8 and I was playing with the X and Y dimensions while standing in the overworld(about 90% sure it was in overworld) teleport, then it crashed right after supposedly TPing. On server reboot I respawned in overworld about 200 blocks away 15 blocks in a dirt, and suffocated.

Can't reproduce.

Crash log: http://pastebin.com/2QKr4V9x

**Comment by maruohon** [comment]
Hmm, I have seen the occasional crash similar to this one every now and then. Not sure if it's something in vanilla or maybe I have something wrong with my TP code, in which case this might be related to the other issue about the Ender Porters...

Could you give me the coordinates of the overworld portal you were using when it crashed, and also the coordinates where you spawned at after relogging? And maybe also the coordinates of the destination portal in the nether if you know it. It might help me determine how it was trying to move/teleport you when it crashed. Because it seems that it moved you inside the same dimension, but didn't change the dimension?

I'll close this issue since it can't really be anything specific to the Portal Scaler itself, because it uses the same TP code as all my other TP things. I'll try to look into the TP code (and thus the other open issue) after I clear some of the other items on my TODO list.

**Comment by maruohon** [comment]
Oh and also, in the crash log, those messages about you moving too quickly every few seconds, are those you using the Portal Scaler? Were you just going back and forth using the same scaling setting? Or are those something else?

**Comment by c0rn3j** [comment]
Sadly I can't give you the coords where I spawned and suffocated as I didn't think of taking them, so I guess the portal coords are useless.
> are those you using the Portal Scaler 
yup yup, was teleporting back and forth with the portal scaler with different settings.

> it seems that it moved you inside the same dimension, but didn't change the dimension?
I think so but I'm not 100% sure of it. I'll get you the coords if this happens again.
