### ISSUE TITLE
[Suggestion] Chat output when using Link Crystal/Porter to set new location

### ISSUE THREAD

**Issue by c0rn3j** [maruohon/enderutilities#24]
Would be awesome to have this feature as I seem to accidentally set location with the Ender Porter without even knowing about it.

**Comment by maruohon** [comment]
Hmm, I could add this, but I would also add a config option for it because personally I wouldn't use it, I generally don't like things that spam the chat with mod-related messages.
However, on my TODO list for the next release (as requested my someone else due to the same circumstances :p) is also adding a "Locked" mode to the location-bindable items, which will prevent binding them to new locations accidentally (ie. while the item is "Locked").

**Comment by c0rn3j** [comment]
Just had an idea, how about you add distinctive sound to the Link Crystal and Ender porters when they set a location? Wouldn't spam the chat and I think it'd be very obvious to everyone.

**Comment by maruohon** [comment]
Yeah I could do that. The mod in general has the issue of lack of proper sound effects, I'm using the enderman teleport sound for a silly amount of things :D Would be nice to some time make/get proper distinct sound effects for things...

**Comment by maruohon** [comment]
Well since those commits didn't close this... I guess they need the magic word "Fixes"?
