### ISSUE TITLE
No access to baubles with Handy Bags

### ISSUE THREAD

**Issue by ImperaServ** [maruohon/enderutilities#26]
Playing with Baubles and Ender Utilities (1.10.2/0.6.5). Love the Handy bag but when I carry one I can't access my Baubles. Is there a way to add compatibility?

**Comment by maruohon** [comment]
I now added the Baubles button to the Handy Bag GUI, it will be in 0.6.6+.

Until then there are two ways to access the Baubles inventory: open the regular player inventory instead of the Handy Bag by sneaking while opening your inventory, or use the Baubles hotkey (B by default) to open the Baubles inventory directly instead of using the regular inventory hotkey.
