### ISSUE TITLE
enhanced functionality for happy chest

### ISSUE THREAD

**Issue by DoomSquirter** [maruohon/enderutilities#29]
probably asking alot here but my favorite quarrying go-to now is combining a rftools builder, a good power supply input to keep it filled, and a happy chest with a 12 card in it.  

One common thread tho, with this circumstance and using them for storage bus-like network connects ala storage network, etc...  is that the active card is the only thing that receives items.  

Is there any possible way to get them to act as one large inventory for stuff coming in?  I.e. fill first card, then next etc?  Maybe possibly a gui button to change the behavior?

**Comment by maruohon** [comment]
Sure it would be possible, but... hmm. I think that it would make the chest a bit confusing if it can use the non-selected cards too. But my main concern is that this would be quite a major change to the code and I'm rather worried that it might introduce new nasty bugs to it, and I'd rather not change it now that they seem to work properly. It would also probably make them a tiny bit slower for automation to access, so that would be another negative outcome of the change.

Using the Extended Handy Chest with a 12 B card should still offer storage for around 500k items even using that one card, and in my opinion even that is already quite a silly amount of storage in one block :P

**Comment by DoomSquirter** [comment]
let's just say I have a voracious appetite when it comes to quarrying and I'm an extreme hoarder :)  

But yeah, you are correct.  12b cards in there are insane for storing lots of stuff, especially with no DSU's around yet.  stacking 4096 items per stack in there is great for quarries for example.  

Nicest thing tho is not to have to take all the stf out but just remove a card and put another one in.  

I guess reason for my issue came about when I realized I had made 20 or so handy chests (largest size) but had to make largest size because it held the most amount of stacks, but it had slots for 4 cards which I never used since each chest was it's own inventory, either by hooking up to storage bus or on quarry.  No big deal tho, it's definately one of my favorite blocks in your mod, only bested by the handy bag.

**Comment by maruohon** [comment]
These type of "slotted inventories" (by which I mean that the GUI has each slot separated in a chest-like manner, and not virtually combined like AE-type storage solutions do) aren't that great for mass storage of one type of item anyway. So I might just go ahead and add a DSU-like storage block which only has one slot, but can hold 2 billion items in that slot like the DSU did. (I also have basically exactly that type of Barrel blocks in the Autoverse mod, but they currently only go up to 32k items per barrel, plus the mod is still in early alpha and no items even have recipies added yet...)

The question is, would it be considered "too OP"/too much storage in one block if the DSU-like block actually had more than one slot, say 3 or 5 slots in the same block? Maybe you could craft 3 of the one-slot variants into a 3-slot variant or something, to increase the cost a bit, but the same OP-ness issue would still remain.

**Comment by maruohon** [comment]
I'm closing this, as I won't add this functionality. I just think it goes against the design philosophy of the chest.
