### ISSUE TITLE
I'm not sure who's at fault here, but...

### ISSUE THREAD

**Issue by BrisingrAerowing** [maruohon/enderutilities#33]
I mined some Naquadah Ore from SGCraft with a Fortune 1000 Diamond Pickaxe (I have cheats enabled, and switched from creative to survival), but the gems from said ore sometimes do not stack IF they are placed into a Handy Bag from the inventory, but always do when inserted from the hotbar. Stacking is hit or miss within the handy bag as well until I move the gems into the hotbar and put them back. None of the gems have any NBT associated with them.

It might be SGCraft's fault as well, but since the items are identical (According to JEI and the Advanced Tooltips), I am leaning towards this mod being at fault.

Minecraft 1.10.2
Forge 12.18.2.2151
Ender Utilities 0.6.5
SGCraft 1.13.1

**Comment by BrisingrAerowing** [comment]
I just found that if I hover over the old, non full stack then move the gems to and from my inventory, it works. So this might be SGCraft's fault after all.

Paging @gcewing

**Comment by BrisingrAerowing** [comment]
Toying around with this some more, and it seems to be a desync issue. I can pick up a stack and place it on another, and the stack I am holding will go into the stack I clicked on BUT won't be removed from my hand.  Closing and reopening the handy bag seems to resync it and causes the phantom stack to disappear.

Weird.

**Comment by BrisingrAerowing** [comment]
Yup. It's a desync issue. The same thing happens with redstone.

**Comment by maruohon** [comment]
Wait, are you saying vanilla redstone also has desync issue in the Handy Bag? O_o

There was a similar stacking issue/glitch/ghost items on the client side with the Blood Magic teleposer foci (or whatever they are called) a while back. It was caused by Blood Magic accidentally creating an empty NBT compound tag to the items on the client side when they were hovered over and it tried to grab the tooltip. This then results in the client side Ender Utilities inventory code to think that the items can't stack with ones that don't have that empty tag, but the server side is what ultimately knows what is actually going on and decides what has actually happened, so re-opening the GUI re-syncs everything from the server to the client.

But if this happens with redstone... does it happen with EVERYTHING? Or do you know if some mod might be adding an ItemStack capability to certain items or something? Or maybe another mod has a similar bug with getting tooltips? Does anything add any special functionality or tooltips to redstone?

**Comment by gcewing** [comment]
I can't imagine what SGCraft could be doing to cause this.
Naquadah ore is a perfectly ordinary item, no special data
associated with it at all.

-- 
Greg

**Comment by maruohon** [comment]
It is also possible that some other mod could be interfering with things. Is this a large modpack? Does this happen reliably all the time in your pack/world? Are you also able to reproduce this if you make a new instance and a test world where you have only Ender Utilities, SGCraft and JEI installed? If it doesn't happen there, then it is most likely some other mod interfering with my Container/GUI...

In that case, to find out the cause, you would have to do something like either start with an empty instance or a **copy** of your main modpack instance and start adding or taking out mods until you find the one with which the issue starts appearing. It's probably easier to start with an empty instance to avoid the complaints about missing mods each time. Then throw in a small amount of mods at a time until the issue starts appearing. Unfortunately that can be rather tedious work...

**Comment by BrisingrAerowing** [comment]
As I have over 200 mods, that might take a while.

I only started seeing it after updating to the Forge version I posted, and now I am seeing it in other inventories/GUIs as well (from Vanilla and other mods), so it may be a Forge issue. The previous Forge version I used didn't have this issue (I think), so I will try going back to it and see what happens.

**Comment by maruohon** [comment]
Hmm, well at least for me in a minimalistic test instance, the Handy Bag inventory works perfectly normal with the latest Forge build 2179.

**Comment by BrisingrAerowing** [comment]
I am on 2179 now, and I am about to go out mining, so we will see what happens.

I still need to build the rest of my bunker as well. That's going to take several days, at least (real world days, not in game days).

**Comment by BrisingrAerowing** [comment]
I am no longer seeing this. I will chalk this issue up to a Forge bug and close it.
