### ISSUE TITLE
Handy bag rendering issue pt 2

### ISSUE THREAD

**Issue by Artemis-E** [maruohon/enderutilities#34]
With Handy bag open FTB utilities not visible. I can sneak open my inventory and still see it though.

**Comment by maruohon** [comment]
Well, it seems that the FTBUtilities widgets also don't appear in any other vanilla GUIs than the player inventory, so they are probably specifically made to check for the regular player inventory.

So unless they have an API for enabling it on other GUIs, there isn't really anything I can do. And in any case I would rather not add another (although optional) dependency to my mod just to enable rendering it... especially because, like you mentioned, you can still access it via the regular inventory by just sneaking while opening the inventory.
