### ISSUE TITLE
Upgrading Handy Bag Destroys Memory Cards and Contents

### ISSUE THREAD

**Issue by Aedda** [maruohon/enderutilities#36]
Steps to reproduce:
1) Make a Handy Bag
2) Insert Memory Card (I used a 12B)
3) Upgrade to Large
4) Memory Cards and Contents will be wiped

Version: enderutilities-1.10.2-0.6.5

**Comment by maruohon** [comment]
This has actually been fixed in commit 06bac2d32d, but since I haven't made a new release since last July, that fix (and many other fixes...) still aren't in a released version...

And sorry about the presumed item loss... >_>

**Comment by Aedda** [comment]
Item loss was thankfully minimal, and your mod is awesome despite the bugs.

**Comment by maruohon** [comment]
I think I'll actually try to run a set of testing and get a 0.6.6 bugfix/feature tweak release out today. I was kind of going to hold off and cram some new stuff in and release it as a 0.7.0. But since there have been quite a bunch of feature tweaks/additions to old items, and some bug fixes in these several months since the previous release (and I don't know how long adding the new things will take still...), I think I'll go ahead and release a 0.6.6 instead to get these fixes etc. available for players.

**Comment by Aedda** [comment]
Oh I was just referring to "that fix (and many other fixes...)" :D

**Comment by maruohon** [comment]
Ah okay, hehe :D

**Comment by maruohon** [comment]
The fix to this was included in the release 0.6.6.
