### ISSUE TITLE
suggestion/ question  for the Handybag

### ISSUE THREAD

**Issue by HeavyDeception** [maruohon/enderutilities#38]
I was wondering if there way to have it keep putting Items in the bag with out being on the card that has that item in it?

**Comment by maruohon** [comment]
You mean auto-pickup items into non-selected Memory Cards?

The answer is no. And I also won't add that functionality, sorry. The reason is that it would both make the bag even more confusing for the players, and more importantly, it would make the code even more complicated and introduce several issues and potential bugs. It would also increase the amount of work the server has to do to handle all of the bag's functionality.

**Comment by HeavyDeception** [comment]
@maruohon I see well thanks for explaining.

**Comment by maruohon** [comment]
Oh btw, you can sort of get around that limitation by simply having multiple Handy Bags in your inventory instead, and have those Memory Cards divided among them.
Or if this is for mass storing items from a mining trip or something similar, then the Item Pickup Manager with the remote transport feature might be useful too
