### ISSUE TITLE
1.11.2 Port?

### ISSUE THREAD

**Issue by Thiana** [maruohon/enderutilities#40]
Hi,

Will you be updating to 1.11.2? If so, is there a general eta? Thank you.

**Comment by maruohon** [comment]
I will update to 1.11.2 as soon I finish the content update I'm currently working on for 1.10.2, so that I don't have to do the 1.11.2 port twice or in multiple phases, as the ItemStack changes are really easy to miss and can cause many bugs that might go unnoticed for some time. So I want to go through my code and do those ItemStack related changes all in one go.

Unfortunately I seem to get features finished a lot slower than I'd like and what I would imagine before starting work on them. That's why I can't give any kind of meaningful real ETA, simply a "as soon as possible, but likely not in a couple of weeks at the very least". It's just that that same "as soon as possible" has been the case pretty much since the release of 1.11 already... >_>

I am rather frustrated and anxious about how long it has been since the release of 1.11 already, and I still haven't ported EnU... I would actually really need the WotLB myself too for a project I'm working on in 1.11.2, so that's an additional personal motivator :P

**Comment by Thiana** [comment]
I _need_ my wonderful backpack :) Having to use others.... *whimpers* 

Though the super wand, swapper and memory chests would be lovely too :)

It's nice to know the port on your list though. Thanks :)

**Comment by maruohon** [comment]
Let's leave this open in case others would also report it. I'll close it when the port has been released.

**Comment by maruohon** [comment]
The mod is now finally out for MC 1.11.2.

**Comment by Thiana** [comment]
Thank you :)
