### ISSUE TITLE
Handy Bag Sorting is Borked with certain items

### ISSUE THREAD

**Issue by BrisingrAerowing** [maruohon/enderutilities#41]
Trying to sort a handy bag page with certain items causes some rather odd behavior, and doesn't actually sort anything:

![2017-05-05_23 11 30](https://cloud.githubusercontent.com/assets/250409/25769483/6f37f196-31e8-11e7-9ce0-845f84a20cd0.png)

![2017-05-05_23 11 33](https://cloud.githubusercontent.com/assets/250409/25769487/79cdaf6a-31e8-11e7-85c1-afbf73c87301.png)

Clicking the sort button just toggles between those two layouts.

(Those canisters are from the Pressure Pipes mod).

**Comment by maruohon** [comment]
Hmm, okay... I'm going to need more information...

* Are ALL of the canisters in the separate slots in the first picture actually different items?
* And then the sort splits them up and then combines them again?
* Do you know if the canisters have NBT data or Capabilities on them, or just different metadata/damage values?

If this is on single player, could you send me your `level.dat` file (which contains the player's inventory) so that I could test this out with your bag and the canisters you have. Or if this is on a server, if you have access to your player data file, then that one. Thanks.

**Comment by BrisingrAerowing** [comment]
The canisters use NBT to store the fluid name and the quantity. Each canister stack has a different type of fluid, or in the first (largest) stack, they are empty.

The sort only splits/combines the empty ones, and leaves the full ones in the same (relative) slots.

Here's the level.dat

[level.dat.zip](https://github.com/maruohon/enderutilities/files/981022/level.dat.zip)

**Comment by maruohon** [comment]
I found and fixed the issue.

Since you mentioned "and doesn't actually sort anything" earlier: the sort feature in my inventories is a rather basic sort, which sorts items according to only 3 criteria:

* Any blocks (in code, items that are `ItemBlock`s) are sorted/moved to the begiinning of the inventory, and the rest of the items come after those blocks
* The items are sorted based on their registry names first
* In case there are items with identical registry names in several slots, then those are sorted based on their metadata/damage value

This means in your case, that none of the canisters will ever switch relative positions, because they are all the same item and thus the same registry name, and they all have the same metadata of 0, since they ONLY store data in NBT.

There is no easy generic way to meaningfully sort them based on NBT data. It would pretty much require adding a special case/separate rule for NBT-based sorting for each and every item that exists in any mod.

**Comment by BrisingrAerowing** [comment]
I figured that. I still can sort them as I want to easily enough.
