### ISSUE TITLE
[Suggestion] Allow automation of all pages in Handy Chests

### ISSUE THREAD

**Issue by BrisingrAerowing** [maruohon/enderutilities#43]
Currently automation systems (Hoppers, Item Conduits, Pipes, etc) can only insert into and pull from the currently selected page in a Handy Chest. I would like to be able to toggle allowing such automation systems to insert into all pages of a Handy Chest. Basically, when a page fills up the automation system will automatically start inserting into the next available page. Also, if a chest has all slots containing items, but the stacks aren't at the maximum size, inserting an item would cause the chest to check all pages for a matching stack, and insert the item if it finds one.

This would allow for having massive storage systems for various farms, for example.

**Comment by maruohon** [comment]
This has been previously discussed in #29.

In short:
* I most likely won't add/change this functionality. It goes against the design of the chest, where you can select one of the cards to access at a time. Personally I actually would NOT want the chest to access the other cards that are unselected. And adding another option to select the mode would just make things more complicated for the GUI and the player (and the code of course).
* It is also implemented so that there is an inventory class, which loads the inventory contents from, and saves them to a specific "container item", which in this case is the active Memory Card.
* To use all cards at once, I could/would need to use four inventory classes, one for each card, and then use a CombinedInventoryWrapper around them. Basically it would make the chest slower/more computationally intensive for automation to access. I think it's already somewhat slow compared to most simpler inventories, because it constantly keeps writing the items to the NBT data of the Memory Card item, every time the inventory contents change. (Offtopic: there might be something I could do to avoid that... adding it to my TODO list to take a look at.)

If you need storage for lots of different item types, then the Extended Handy Chest already has over a 100 slots, which each can store up to 4096 items. In total it can store over 500k items on one card.

On the other hand, if you need to store a large number of a few item types, then I'd recommend using the Massive Storage Unit or the Massive Storage Bundle instead. By default they can store up to exactly 1 billion items per slot (configurable, maximum is about 2 billion, ie. the max value of a 32-bit integer). They also won't suffer from the slower inventory code of the Handy Chest like I mentioned above.
