### ISSUE TITLE
Dupe glitch when using the dolly

### ISSUE THREAD

**Issue by hisnameislongarms** [maruohon/enderutilities#45]
By "picking up" a chest with dolly added by the mod, all the contents come out as items you can pick up. Then when the chest is re-placed the contents of the chest are still in there. You can then take them out or put the duped items back in.

**Comment by maruohon** [comment]
That should, and does not, happen in my dev environment with just Forge and EnU. Something must be changing how one of the fields in the `World` class works.

I need more information about the pack, MC version etc. Is this on a server, or otherwise using for example Sponge, or maybe some protection mods? Was it a vanilla chest, or what type?
