### ISSUE TITLE
Can't put Bits from Chisels and Bits in the Nullifier

### ISSUE THREAD

**Issue by ShaunDreclin** [maruohon/enderutilities#54]
Ender Utilities 0.7.2
Chisels & Bits 14.4

I tend to have way more bits than I can handle and the nullifier would be perfect for that, but it wouldn't let me put bits in any of the slots :c

**Comment by maruohon** [comment]
This is because of one of the restrictions that I have in place to try to avoid putting in "other usable items" than items for blocks. But the way things are in Minecraft, that check isn't ever really going to work properly, ie. **only** being able to put in items for blocks in the Nullifier. So I can probably remove the "no-NBT-data" check from it, which should then allow the C&B items in.
