### ISSUE TITLE
[Request] Ender Elevator Slab in upper position

### ISSUE THREAD

**Issue by BrisingrAerowing** [maruohon/enderutilities#55]
Currently the Ender Elevator Slab can only be placed in the lower position. I am currently using upside down slabs as my flooring, and would like to use the Ender Elevator Slab to go between levels, but not being able to place it in the upper half of a block is preventing that. Is there any particular reason that wasn't added?

**Comment by maruohon** [comment]
Not really, I was considering it, but simply didn't implement it. So I'm assuming you don't want it to be sticking out on the bottom visually? Are you using the camouflage feature? Because you can camouflage them using an upper-half slab, regardless of which version of the elevator you use. Then simply the actual collision box of the elevator will "stick out invisibly" from what the rendered model is. Although I think it might not be possible in practice to apply the upper-half slab camo to the slab and layer variant though... because you need to click on the upper part of the elevator block for it to become an upper-half slab, the same way you would place the slab against another block to place it as an upper-half variant.

But I can implement the upper-half slab and layer variants of the elevator for the next version. I hope you are in 1.12, because I probably won't do it for older versions anymore (I'm trying to stop supporting them with anything other than critical fixes, to lower the amount of extra work...).

**Comment by BrisingrAerowing** [comment]
I plan on switching to 1.12 as soon as Mekanism updates (I love the portals it adds. Especially the fact they can teleport any ridden entities with their riders). I can live without this until then.

**Comment by maruohon** [comment]
Alright. I won't bother backporting this then... after I implement it in the first place.

The EnU Portals (like all the TP items too) should also TP any entities with their riders... but of course they are nowhere near as pretty and/or interesting as the Mekanism ones...

**Comment by BrisingrAerowing** [comment]
I never really figured out how the EnU portals work. I also like that you can place a track within the Mekanism portal frame and it still works.

**Comment by maruohon** [comment]
Ah, cool. I've never played with Mekanism myself... nor with that many other mods in general. Last time I actually properly played modded myself was in February 2015 in my custom 1.7.10 pack...

The EnU portals are a simple one-way teleportation device. You take a Link Crystal, link it anywhere, and then place it inside the Portal Panel. That Portal Panel needs to be placed on the portal frame, or at least be connected to it via a fully continuous "path" of frame blocks. Meaning that you can have the panel be elsewhere, if you connect it via the frame blocks inside your building's walls for example. Then just select that destination using the 8 buttons (ie. press the one where your LC is), and then activate the portal using the center button.

**Comment by BrisingrAerowing** [comment]
I see. I'm messing with a 1.12 instance now (Mekanism updated to 1.12.1, then quickly added 1.12 support. There doesn't seem to be too many changes between those versions.) I'm missing a few mods I like, but I did find that Chococraft is now being maintained again. 😍

**Comment by maruohon** [comment]
These were added as of 1f1af7c. I'll probably make a new release in the next couple of days or so.
