### ISSUE TITLE
Can't change restock / pickup modes in the handy bag

### ISSUE THREAD

**Issue by BrisingrAerowing** [maruohon/enderutilities#73]
As per title. The buttons do absolutely nothing other than click.

Version 0.7.10

**Comment by maruohon** [comment]
Do you have a card selected? Those were changed to be stored on the cards in 0.7.9.

**Comment by BrisingrAerowing** [comment]
Yes. I have 4 memory cards in it. None of them work.

**Comment by BrisingrAerowing** [comment]
It works in my more minimal instance, so I'm guessing this is a mod compat issue.

**Comment by maruohon** [comment]
That would be a *really* strange compat issue though... I can't think of any reason why the latest versions wouldn't work, if 0.7.8 and earlier works in the same pack?

**Comment by BrisingrAerowing** [comment]
I can test in in my main pack again. I think it may be a Forge related issue, as that pack is on an older version, while the minimal pack is on a much newer one.

**Comment by BrisingrAerowing** [comment]
I've just had this happen again, and found out some more info. If the memory card is fresh (i.e. pulled out of creative / JEI), then the buttons don't work. BUT as soon as any item is put into the card, the buttons start working again. Not sure about crafting the cards (I usually play in creative).

**Comment by maruohon** [comment]
Oh interesting! Now I can reproduce it too.

And after some looking around I found the issue. It's now partially fixed. There is still the issue that if you do this:
* Take a fresh Card without NBT
* Change the modes on it
* Either take the card out, or put an item on it

it will wipe the mode data from that new card in those two cases. It has to do with the item-based modular inventory stuff, and that part of the code is rather complex and fragile, so I don't want to go messing around in there trying to fix that minor issue...

And a complete rewrite of that stuff is planned for 0.8.0 anyway (whenever I have the time to start on that...), because I want to move the item-based inventories be stored in a separate system, instead of storing everything in the ItemStack NBT data. That would reduce server CPU usage when handling inventories containing these item storage items, and it should solve the issues with too much NBT on items, plus the related client sync issues.
