### ISSUE TITLE
[Suggestion] Reverse punch and shift-punch functions on barrels

### ISSUE THREAD

**Issue by DarkYuan** [maruohon/enderutilities#81]
Similar to other mods with barrel-type storage (JABBA, Storage Drawers...) normally a neutral punch is the way to take out 1 item, and the shift-punch takes out a whole stack. When using Ender Utilities, having punch take out a stack feels counterintuitive. The default should be the other way around, with perhaps a config to swap them.

**Comment by maruohon** [comment]
Sorry about not responding to this issue sooner, I meant to check this with JABBA first as I was sure this is the way it worked in it, but then I forgot all about this issue... Anyway, I just checked with the JABBA barrels in MC 1.6.4 (in the Agrarian Skies mod pack at least it worked this way), and indeed I remembered right, with sneaking you take out single items, and without sneaking you take out stacks.

But in any case, yeah I can add a config option for that. I'm however not going to change the default behavior, because that would be a sudden unneeded change for those who have gotten used to the current way of working.
