### ISSUE TITLE
Void_Pickaxe, Unable to texture it for texture pack.

### ISSUE THREAD

**Issue by CaptainStalfoss** [maruohon/enderutilities#84]
Hi, love the mod, but i generally play with dokucraft like item graphics.
Now i already made textures for most enderutilities items, witch work fine.

But the void pickaxe wont work, i gave it new textures but now it looks like glitchy mess in game, I cannot find any other textures for it.

I assume it is due to the glow effect it has, But there really should be a way to have such effects and still allow it to be re textured.

**Comment by maruohon** [comment]
It uses the vanilla Lava texture for the middle part/glow effect. Did you change the model of the item? It uses a custom json model to piece together the different parts of the item, to include the lava texture bits in the middle. If your re-textured version uses a different shape/relative dimensions than the original, then the original model won't work properly and you would have to redo the model files for it, or just replace the models with a basic item model instead of using the lava texture in it like the original does.

If this is not the case, then could you post a screenshot of how it looks, and also the texture and any relevant model files you have for it, so I can take a look why it might not work properly?

**Comment by CaptainStalfoss** [comment]
Never really dealt with json modeling, i mostly just work with pixels.
and yeah it does use a different texture, here's what it looks like: 

![testmf](https://user-images.githubusercontent.com/38992378/52135233-a12a1780-2645-11e9-8e63-9e28a832f6f7.png)

**Comment by maruohon** [comment]
Looks like it doesn't use the glint/lava effect at all? Then you should just override the item models for the void pickaxe in the resource pack.

So basically, in https://github.com/maruohon/enderutilities/tree/master/src/main/resources/assets/enderutilities/models/item there are 4 models for the void pickaxe's different states. Just include model files in the same locations in your resource pack, but basically copy paste the originals and then modify them so that you basically remove the custom `elements` array, and the original `textures` object, and instead use basically
```json
    "parent": "enderutilities:item/standard_tool",
    "textures": {
        "layer0": "enderutilities:items/void_pickaxe_whatever"
    },
```
in their place, I believe. If that doesn't work, then also try `"parent": "minecraft:builtin/generated"` instead of the enu `standard_tool`.

**Comment by CaptainStalfoss** [comment]
Yay that did it, Thanks a lot man <3
also thanks for an amazing mod.
