### ISSUE TITLE
Tinker's integration

### ISSUE THREAD

**Issue by Gaelan** [maruohon/enderutilities#9]
It would be great if there was some material and/or modifier that allowed using this mod's abilities with TCon tools. If you'd like, I can try my hand at implementing this.

**Comment by maruohon** [comment]
Do you mean the mined item teleport into player or remote inventories?

I haven't looked that much at how Tinkers handles modifiers and if they have an API for the tools.
But at least the remote inventory part of it would probably not make that much sense in Tinkers tools, since the way I have my items done (with the modules) means that you couldn't store the target in the Tinkers tool without either re-implementing the target and/or module code on the Tinkers tools, or otherwise implementing that again on them.

May I ask what kind of a usage situation are you thinking of exactly, why you don't want to just use the tools from ender utilities? I have thought about adding hammers for 3x3 mining, but haven't really decided for or against it yet. I do realize that Tinkers tools are probably better and more convenient and have a fun crafting and maintenance mechanic on them and are thus probably often preferable in general use. So I see my tools as kind of a special case utility, if you are working in a void world or otherwise in a situation where you would want the drops instantly in your inventory.

In either case, I'd say that I for sure won't be adding any compatibility for Tinkers in the 1.7.10 version anymore. Tinkers for 1.8.x is well under development, is a complete rewrite and thus probably works differently when it comes to the tools, their parts/upgrades etc. So if some support will be added, it will be for a 1.8.x version. (Which I too still need to re-make and finish...)

**Comment by maruohon** [comment]
I'd say this is quite unlikely to ever happen, it doesn't really fit in with my view of the mod as it is.
